language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: 
            - g++-8
            - p7zip-full
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install: eval "${MATRIX_EVAL}"
install: mkdir -p build/opencv/ && cd build/opencv/ && cmake -DCMAKE_INSTALL_PREFIX=install/ -G "Unix Makefiles" ../../3rdparty/opencv_contrib/ && cmake --build . --config Release && cd ../../
script: cd build/ && cmake -DCMAKE_INSTALL_PREFIX=install/ -DOpenCV_DIR=build/opencv/install/share/OpenCV/ -G "Unix Makefiles" .. && cmake --build . --config Release --target install && cd ..
before_deploy: 7z a ArucoUnityPlugin-$TRAVIS_TAG-Linux.zip ./build/install/*
deploy:
  provider: releases
  api_key:
    secure: "YMgbglG/gPJ4Pdzf6zFauiKdtrpGe6thuoCBn1JbAdFhZPM45lyD9RxhXHZpX7SdYvUVoglD/qnGjShk2ahBMYXHEnRvZzIHdKGrLnVXS73eYuGNNizwA5cWV3biUzgRJa3cjEBNStBA0KSeCtisi68piYA0HqB9jGVKPosdjXtt1sBUEujQgnWJXO/y4cmBEr5aZlOqolHdtJJStDmzlHwqvqQV/KtTEC3BHrGe/98la7Cy1Enzq2q+bXXjBvU1/OVv0YphW14w16uvDE3Ngiw2+gq8eSUsqq/Z5suXTXWphvB+jAJIVF4V98h/4thU0YY1JRlIaYwqvfpb7dGQIttozAa1RgTYsDxZgkNLYiAPbDvelZHUrwfIgcIhhikCTaA1paK09e+BZ2FM0osNSWdCfbZ13ZcthGe0zb/Q9eMFu0P74ml18ZmUgA+VfzoEEulxNczkJWUQliZ0Xjzp0YtfEDywjfhOvEmZO6xXUu3Xh6rpG/dtJIam7ACajyQJBhyFjyy65gnYnyl8tLcXo1CQ+N9Kmz4IpHjCSyMumg4Ixhe14IK7YUKpzTxVA5jKoRydLQDtJS0QlKshHO4ycSBVEucW2xtX/UNwcaPuyalnrv8z2vS/j+lquWauxZUHEanass4VZF6n2tSCQLBUd+izZZ7Bj8tduM4jd3jnCg0="
  file: ArucoUnityPlugin-$TRAVIS_TAG-Linux.zip
  skip_cleanup: true
  on:
    tags: true