language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install: eval "${MATRIX_EVAL}"
install: mkdir -p build/opencv/ && cd build/opencv/ && cmake -DCMAKE_INSTALL_PREFIX=install/ -G "Unix Makefiles" ../../3rdparty/opencv_contrib/ && cmake --build . --config Release && cd ../../
script: cd build/ && cmake -DCMAKE_INSTALL_PREFIX=.. -DOpenCV_DIR=build/opencv/install/share/OpenCV/ -DArucoUnity_DIR=.. -G "Unix Makefiles" .. && cmake --build . --config Release --target install